data_cfg:
  dataset_name: Gait3D
  dataset_root: /data/Gait3D-pkls/Gait3D-links-pkl
  dataset_partition: ./datasets/Gait3D/Gait3D_Diff.json
  num_workers: 1
  data_in_use: [True, True] # heatmap, sil
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: Gait3D

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 100000
  save_name: SkeletonGait_Diff_Large
  eval_func: evaluate_Gait3D
  sampler:
    batch_shuffle: false
    batch_size: 1
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weights: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weights: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: DiffGait_Large
  # diffusion_phase: True
  pretrained_diffgait: /home/gsx/mfx/OpenGait-master/output/Gait3D/DiffGait_Large/SkeletonGait_Diff_Large/checkpoints/SkeletonGait_Diff_Large-100000.pt
  diffusion_phase: False

optimizer_cfg:
  lr: 1.0e-4
  momentum: 0.9
  solver: Adam
  weight_decay: 5.0e-4

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 40000
    - 80000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: SkeletonGait_Diff_Large
  sync_BN: true
  total_iter: 100000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8 # TripletSampler, batch_size[0] indicates Number of Identity
      - 8 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 10 # fixed frames number for training
    frames_skip_num: 4
    sample_type: fixed_ordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: RandomPerspective
          prob: 0.2
        - type: BaseSilTransform
        - type: RandomHorizontalFlip
          prob: 0.2
        - type: RandomRotate
          prob: 0.2

