data_cfg:
  dataset_name: Gait3D
  dataset_root: /data/Gait3D-pkls/Gait3D-links-pkl
  dataset_partition: ./datasets/Gait3D/Gait3D_Diff.json
  num_workers: 1
  data_in_use: [True, True] # heatmap, sil
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: Gait3D

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 60000
  save_name: DiffGait_DDPM
  eval_func: evaluate_Gait3D
  sampler:
    batch_shuffle: false
    batch_size: 1
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weights: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weights: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: DiffGait_DDPM
  # diffusion_phase: True
  pretrained_diffgait: /home/gsx/mfx/OpenGait-master/output/Gait3D/DiffGait_DDPM/DiffGait_DDPM/checkpoints/DiffGait_DDPM-60000.pt
  diffusion_phase: False

optimizer_cfg:
  lr: 0.0002
  momentum: 0.9
  solver: Adam
  weight_decay: 0.000

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 40000
    - 80000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: DiffGait_DDPM
  sync_BN: true
  total_iter: 60000
  sampler:
    batch_shuffle: false
    batch_size:
      - 4
      - 4
    frames_num_fixed: 8
    frames_num_max: 50
    frames_num_min: 25
    sample_type: fixed_unordered
    type: TripletSampler

